---
title: "test_jeu_de_donnees"
author: "manon santrisse"
date: "08/02/2022"
output: pdf_document
---


```{r}
library(dplyr)
library(ggplot2)
library(corrplot)
library(readxl)
library(FactoMineR)
library(factoextra)
library(cowplot)
library("NbClust")
library(missForest)
```



```{r}
jeu1=read.csv("political-regimes.csv",header=TRUE,sep=",")

jeu1=jeu1[jeu1$Year==2020,]

nrow(jeu1) #on a 179 pays en faisant ça, pour chacun on a un numéro qui correspond à son niveau démocratique entre 0 et 3, plus c'est proche de 0, plus c'est autoritaire

jeu1=jeu1[,-2]
jeu1=jeu1[,-2]
head(jeu1)

#En faisant ça certains pays ont sauté comme par exemple Baden Bavaria 
```

```{r}
jeu2=read.csv("age-of-democracies.csv",header=TRUE,sep=",")
jeu2=jeu2[,-2]
jeu2=jeu2[,-2]
head(jeu2)
```

```{r}
#j'essaie de combiner les jeux 1 et 2
data=inner_join(jeu1,jeu2,by="Entity")
colnames(data)[3]="Age of democracies in 2015"
head(data)
nrow(data)
```

```{r}
jeu4=read.csv("child-mortality.csv",header=TRUE,sep=",")
#jeu4=jeu4[jeu4$Year==2021,]
#jeu4=jeu4[,-2]
#jeu4=jeu4[,-2]
#jeu4=jeu4[,-3]
#jeu4=jeu4[,-3]
#jeu4=jeu4[,-3]
print(jeu4)
```

```{r}
#These Human Rights Scores indicate the degree to which governments protect and respect human rights.
human_rights=read.csv("human-rights-scores.csv",header=TRUE,sep=",")
human_rights=human_rights[human_rights$Year==2017,]
human_rights=human_rights[,-2]
human_rights=human_rights[,-2]
colnames(human_rights)[2]="human_right"
head(human_rights)
```

```{r}
economic_freedom=read.csv("economic-freedom.csv",header=TRUE,sep=",")
economic_freedom=economic_freedom[economic_freedom$Year==2016,]
economic_freedom=economic_freedom[,-2]
economic_freedom=economic_freedom[,-2]
colnames(economic_freedom)[2]="economic freedom"
head(economic_freedom)
```

```{r}
#pas de données récentes pour tous les pays
gender_gap=read.csv("gender-gap.csv",header=TRUE,sep=",")
print(gender_gap)
gender_gap=gender_gap[gender_gap$Year==2000,]
nrow(gender_gap)
head(gender_gap)
```

```{r}
#pas de données récentes pour tous les pays
gender_inequality=read.csv("gender-inequality.csv",header=TRUE,sep=",")
print(gender_inequality)
gender_inequality=gender_inequality[gender_inequality$Year==2015,]
gender_inequality=gender_inequality[,-2]
gender_inequality=gender_inequality[,-2]
colnames(gender_inequality)[2]="gender inequality"
nrow(gender_inequality)
head(gender_inequality)
```

```{r}
#Percentage of children aged 13-15 who reported being bullied at least once in the past couple of months.
bullied=read.csv("bullied-children.csv",header=TRUE,sep=",")
bullied=bullied[,-2]
bullied=bullied[,-2]
colnames(bullied)[2]="pct of bullied children"
head(bullied)
```

```{r}
#Transparency International's Corruption Perception Index. Scores are on a scale of 0-100, where 0 means that a
#country is perceived as highly corrupt.
corruption=read.csv("corruption.csv",header=TRUE,sep=",")
corruption=corruption[corruption$Year==2018,]
corruption=corruption[,-2]
corruption=corruption[,-2]
colnames(corruption)[2]="corruption"
head(corruption)
nrow(corruption)
```

```{r}
#Estimates correspond to the share of the population older than 14 years that is able to read and write.
literacy_rate=read.csv("literacy.csv",header=TRUE,sep=",")
literacy_rate=literacy_rate[literacy_rate$Year==2015,]
literacy_rate=literacy_rate[,-2]
literacy_rate=literacy_rate[,-2]
colnames(literacy_rate)[2]="literacy rate"
nrow(literacy_rate)
head(literacy_rate)
```

```{r}
#The Human Development Index (HDI) is a summary measure of key dimensions of human development: a long and healthy life, a good education, and having a decent standard of living.
HDI=read.csv("human-development-index.csv",header=TRUE,sep=",")
HDI=HDI[HDI$Year==2017,]
nrow(HDI)
head(HDI)
HDI=HDI[,-2]
HDI=HDI[,-2]
colnames(HDI)[2]="HDI"
head(HDI)
```

```{r}
#mean year of schooling : Average total years of schooling for adult population
schooling=read.csv("mean-years-of-schooling.csv",head=TRUE,sep=",")
#head(schooling)
schooling=schooling[schooling$Year==2017,]
#head(schooling)
schooling=schooling[,-2]
schooling=schooling[,-2]
colnames(schooling)[2]="mean_schooling_for_adults"
head(schooling)
```

```{r}
data=merge(jeu1,jeu2,by="Entity",all=TRUE)
colnames(data)[3]="Age of democracies in 2015"
#print(data)

data=merge(data,human_rights,by="Entity",all=TRUE)


data=merge(data,economic_freedom,by="Entity",all=TRUE)

data$`Age of democracies in 2015`[data$`Age of democracies in 2015` %in% "Not a democracy in 2015"]<-0
data=transform(data,`Age of democracies in 2015` =as.numeric(`Age of democracies in 2015`))

data=merge(data,gender_inequality,by="Entity",all=TRUE)


data=merge(data,bullied,by="Entity",all=TRUE)
#head(data)
#nrow(data)

data=merge(data,corruption,by="Entity",all=TRUE)


data=merge(data,literacy_rate,by="Entity",all=TRUE)

data=merge(data,HDI,by="Entity",all=TRUE)

data=merge(data,schooling,by="Entity",all=TRUE)

head(data)
nrow(data)

rownames(data)<-data$Entity

#rownames(data2)
head(data)
print(data)
```



```{r}
#Life expectancy is a measure of premature death and it shows large differences in health across the world.

#The population of many of the richest countries in the world have life expectancies of over 80 years. In 2019 the life expectancy in Spain, Switzerland, Italy, and Australia was over 83 years. In Japan it was the highest with close to 85 years.

#In the countries with the worst health life expectancy is between 50 and 60 years. The population of the Central African Republic has the lowest life expectancy in 2019 with 53 years.

jeu3=read.table("life-expectancy.csv",header=TRUE,sep=",")
jeu3=jeu3[jeu3$Year==2019,]
jeu3=jeu3[,-2]
jeu3=jeu3[,-2]
head(jeu3)
summary(jeu3)
```

```{r}
jeu4=read.table("military-expenditure-as-share-of-gdp.csv",header=TRUE,sep=",")
jeu4=jeu4[jeu4$Year==2019,]
jeu4=jeu4[,-2]
jeu4=jeu4[,-2]
#colnames(jeu4)[2]="human_right"
head(jeu4)
summary(jeu4)
```


```{r}
#The prevalence of undernourishment, as a share of the population, is the main hunger indicator used by the UN’s Food and Agriculture Organization.

#It measures the share of the population which has a caloric (dietary energy) intake which is insufficient to meet the minimum energy requirements defined as necessary for a given population.

jeu5=read.csv("prevalence-of-undernourishment.csv",header=TRUE,sep=",")
jeu5=jeu5[jeu5$Year==2018,]
jeu5=jeu5[,-2]
jeu5=jeu5[,-2]
#colnames(economic_freedom)[2]="economic freedom"
head(jeu5)
summary(jeu5)


```


```{r}
#The map shows the share of the population that is accessing the internet for all countries of the world. Internet users are individuals who have used the Internet (from any location) in the last 3 months. The Internet can be used via a computer, mobile phone, personal digital assistant, games machine, digital TV etc.

jeu6=read.csv("share-of-individuals-using-the-internet.csv",header=TRUE,sep=",")
jeu6=jeu6[jeu6$Year==2017,]
jeu6=jeu6[,-2]
jeu6=jeu6[,-2]
head(jeu6)
summary(jeu6)
```

```{r}
#Share of the population with access to electricity. The definition used in international statistics adopts a very low cutoff for what it means to ‘have access to electricity’. It is defined as having an electricity source that can provide very basic lighting, and charge a phone or power a radio for 4 hours per day.

jeu7=read.csv("share-of-the-population-with-access-to-electricity.csv",header=TRUE,sep=",")
jeu7=jeu7[jeu7$Year==2019,]
jeu7=jeu7[,-2]
jeu7=jeu7[,-2]
head(jeu7)
summary(jeu7)

```



```{r}
jeu8=read.csv("urban-and-rural-population.csv",header=TRUE,sep=",")
jeu8=jeu8[jeu8$Year==2020,]
jeu8=jeu8[,-2]
jeu8=jeu8[,-2]
head(jeu8)
summary(jeu8)
```



```{r}

data3=merge(data,jeu3,by="Entity",all=TRUE)


data3=merge(data3,jeu4,by="Entity",all=TRUE)

data3=merge(data3,jeu5,by="Entity",all=TRUE)

data3=merge(data3,jeu6,by="Entity",all=TRUE)

data3=merge(data3,jeu7,by="Entity",all=TRUE)

data3=merge(data3,jeu8,by="Entity",all=TRUE)

summary(data3)

rownames(data3)<-data3$Entity
summary(data3)
print(data3)


```

#Table de données avec regime politique et Gscore comme variable expliquée 
```{r}
write.table(data3,"data3.csv",row.names=FALSE,sep=";",dec=",",na=" ")
```


