---
title: "R Notebook"
output: html_notebook
---



```{r}
library(dplyr)
library(ggplot2)
library(corrplot)
library(readxl)
library(FactoMineR)
library(factoextra)
library(cowplot)
library("NbClust")
library(missForest)

library(dplyr)
```



```{r}
jeu9=read.csv("dt3.csv",header=TRUE,sep=";",dec=",")
jeu9=jeu9[c(1,12)]
head(jeu9)
```

On combine les jeu de donné data3 avec le gscore

```{r}
jeu2=read.csv("data3-modif.csv",header=TRUE,sep=";",dec=",")
head(jeu2)
data=merge(jeu9,jeu2,by="Entity",all=TRUE)
data=data[-3]
head(data)
``` 


On supprime les pays dont nous n'avons pas l'indice gscore


```{r}
data =data %>% filter(!is.na(gscore))
print(data)
head(data)
``` 




```{r}
colnames(data)[2]="Gscore"
colnames(data)[3]="Age_democratie"
colnames(data)[4]="Droit_de_lHomme"
colnames(data)[5]="Liberte_economique"
colnames(data)[6]="Inegalite_des_genres"
colnames(data)[7]="Proportion_denfants_harceles"
colnames(data)[8]="Corruption"
colnames(data)[9]="Taux_alphabetisation"
colnames(data)[10]="HDI"
colnames(data)[11]="Annes_detudes"
colnames(data)[12]="Espérance_vie"
colnames(data)[13]="Budget_militaire_from_GPD"
colnames(data)[14]="Sous_alimentation"
colnames(data)[15]="Acces_Internet_pers"
colnames(data)[16]="Acces_electricite_pers"
colnames(data)[17]="Pop_urban"
colnames(data)[18]="Pop_rural"
head(data)
``` 



#Table de données avec Gscore comme variable expliquée 
```{r}
write.table(data,"data3_Gscore.csv",row.names=FALSE,sep=";",dec=",",na=" ")
```

